# Request 서비스 메시지임
float32 linear_x
float32 angular_z
float32 dist 
---
# Result 토픽 메시지임 
float32 pos_x
float32 pos_y
float32 pos_theta
float32 result_dist
---
# Feedback 토픽 메시지임
float32 remained_dist
